name: News Crawling and Analytics

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  crawl-news:
    name: Crawl news
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies & Build
      run: |
        npm install
        npm run build
    - name: Crawl News
      run: |
        npx ts-node -r tsconfig-paths/register ./src/scripts/analyzer/index --env=production
      env:
        ENV_MONGODB_URI_CONFIG: ${{ secrets.ENV_MONGODB_URI_CONFIG }}
        ENV_MONGODB_URI_CRAWLER: ${{ secrets.ENV_MONGODB_URI_CRAWLER }}
        ENV_MONGODB_URI_BACK_END: ${{ secrets.ENV_MONGODB_URI_BACK_END }}
        ENV_RUN_CRAWLER_TASK: true
        ENV_TRIGGER_ANALYTICS: false
        ENV_RUN_ANALYTICS_TASK: false
      
  analytic-tpthuduc:
      name: Analytics on Tp. Thu Duc
      if: always()
      needs: [crawl-news]
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies & Build
        run: |
          npm install
          npm run build
      - name: Analytics on Tp. Thu Duc  
        run: |
          npx ts-node -r tsconfig-paths/register ./src/scripts/analyzer/index --env=production
        env:
          ENV_MONGODB_URI_CONFIG: ${{ secrets.ENV_MONGODB_URI_CONFIG }}
          ENV_MONGODB_URI_CRAWLER: ${{ secrets.ENV_MONGODB_URI_CRAWLER }}
          ENV_MONGODB_URI_BACK_END: ${{ secrets.ENV_MONGODB_URI_BACK_END }}
          ENV_RUN_CRAWLER_TASK: false
          ENV_TRIGGER_ANALYTICS: false
          ENV_RUN_ANALYTICS_TASK: true
  
  analytic-quan9:
      name: Analytics on Q9
      if: always()
      needs: [crawl-news]
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies & Build
        run: |
          npm install
          npm run build
      - name: Analytics on Quan 9
        run: |
          npx ts-node -r tsconfig-paths/register ./src/scripts/analyzer/index --env=production
        env:
          ENV_MONGODB_URI_CONFIG: ${{ secrets.ENV_MONGODB_URI_CONFIG }}
          ENV_MONGODB_URI_CRAWLER: ${{ secrets.ENV_MONGODB_URI_CRAWLER }}
          ENV_MONGODB_URI_BACK_END: ${{ secrets.ENV_MONGODB_URI_BACK_END_2 }}
          ENV_RUN_CRAWLER_TASK: false
          ENV_TRIGGER_ANALYTICS: false
          ENV_RUN_ANALYTICS_TASK: true
