name: News Crawling

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        npm install
        npm run build
    - name: crawl
      run: |
        npx ts-node -r tsconfig-paths/register ./src/scripts/analyzer/index --env=production
      env:
        ENV_RUN_CRAWLER_TASK: false
        ENV_RUN_ANALYTICS_TASK: false
